# Generated by Django 2.2.1 on 2019-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='delete',
        ),
    ]
