# Generated by Django 2.2.1 on 2019-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='id_rfid',
            field=models.IntegerField(default=False),
        ),
    ]
