# Generated by Django 2.2.1 on 2019-07-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rfid', '0002_remove_rfid_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='id_alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno'),
        ),
    ]
