# Generated by Django 2.2.1 on 2019-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rfid', '0003_auto_20190702_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='id_rfid',
            field=models.IntegerField(),
        ),
    ]
