# Generated by Django 2.2.1 on 2019-07-03 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rfid', '0003_auto_20190702_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rfid.Rfid')),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
    ]
