# Generated by Django 2.2.1 on 2019-07-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rfid', '0001_initial'),
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rfid.Rfid'),
        ),
    ]
