# Generated by Django 2.2.1 on 2019-07-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='rfid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rfid.Rfid'),
        ),
    ]
