# Generated by Django 2.2.1 on 2019-07-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rfid', '0002_remove_rfid_delete'),
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='id_rfidAlumno',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_rfid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Rfid.Rfid'),
        ),
    ]
