# Generated by Django 2.2.1 on 2019-07-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_rfid',
            new_name='rfid',
        ),
    ]
