# Generated by Django 2.2.1 on 2019-07-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0002_auto_20190702_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rfid.Rfid'),
        ),
    ]
