# Generated by Django 2.2.1 on 2019-07-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0002_asistencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
    ]
