# Generated by Django 2.2.1 on 2019-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0003_remove_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
